### ISSUE TITLE
Results not shown

### ISSUE THREAD

**Issue by marcus-at-localhost** [jk-oster/obsidian-search-for-web#3]
Hi, your extension looks very promising.
I downloaded it from here: https://github.com/jk-oster/obsidian-search-for-web/releases/tag/experimental and installed it.

First bug I noticed was an unstyled settings page. The timestamp in the filename of main.*.css  is different from the one referenced in options.html and the manifest.json

Second, the results are not displayed. 

![image](https://user-images.githubusercontent.com/1337223/211210341-fecdc98f-8f4d-4ddb-a21e-134f336e9f35.png)

The API call was successful, though.

**Comment by jk-oster** [comment]
Hey @marcus-at-localhost , thanks a lot for trying the extension and giving me this feedback!

I need to fine tune the Vite setup because so far I need to update this timestamp manually. The results display bug happend when the "exluded paths" setting was empty - so maybe change that setting and the issue should resolve itself or download the updated version with the fix.

**Comment by jk-oster** [comment]
CSS issue is now solved with the new version
